<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="PRG_TEST" Id="{8fd80737-52d7-48f7-8910-0003a883abff}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM INTERNAL PRG_TEST
VAR
	fbDummyModule : FB_DummyModule;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[(*
CONTAINS CODE NEEDED FOR AUTOMATIC TESTING
*)

// SystemBase is the master program. it controls all underlying modules.
SystemBase();

// Call modules
fbDummyModule(nModuleID:= 1);

// HMI control
// GVL_HMI.fbHMIControl();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>